apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: default
spec:
  version: 8.12.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:

        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: default
spec:
  version: 8.12.0
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    server.basePath: "/kibana"
    server.rewriteBasePath: true
    xpack.security.secureCookies: false
  podTemplate:
    spec:
      containers:
      - name: kibana
        readinessProbe:
          httpGet:
            path: /kibana/login
            port: 5601
            scheme: HTTPS
        resources:
          requests:
            memory: 512Mi
            cpu: 200m
          limits:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: default
spec:
  version: 8.12.0
  count: 1
  elasticsearchRef:
    name: quickstart
  kibanaRef:
    name: quickstart
  http:
    service:
      spec:
        type: ClusterIP
  podTemplate:
    spec:

      containers:
      - name: apm-server
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 200m
