apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: boutique
spec:
  template:
    spec:
      containers:
      - name: server
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: cartservice
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=cartservice,deployment.environment=production
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(HOST_IP):4317
        - name: COLLECTOR_SERVICE_ADDR
          value: otel-gateway-opentelemetry-collector.default.svc.cluster.local:4317
        - name: ENABLE_TRACING
          value: "1"
        - name: OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED
          value: "false"
